//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Up
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string ip { get; set; }
    }
}
